# Github action testing for the rust library with coverage info
# on Merge request and push to master branch
name: test + cov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

      - name: Coverage
        run: cargo tarpaulin --out Xml

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./tarpaulin-report.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true


